apiVersion: v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: default
  labels:
    app: redis
spec:
  replicas: 1
  containers:
  - name: redis
    image: redis:5.0
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    restartPolicy: Always
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: test-redis-config
        items:
        - key: redis-config
          path: redis.configmap