apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: epitechcontent/t-dop-600-worker:k8s
        resources:
          limits:
            memory: "256M"
        envFrom:
          - configMapRef:
              name: postgres-configmap
          - secretRef:
              name: postgres-secret
          - configMapRef:
              name: redis-configmap
      restartPolicy: Always